export const presetLocations = [
  {
    id: "loc-yunusabad",
    nameUz: "Toshkent, Yunusobod tumani (Bodomzor yaqini)",
    nameRu: "Ташкент, Юнусабадский район (около Бодомзор)",
    nameEn: "Tashkent, Yunusabad district (near Bodomzar)",
    districtUz: "Yunusobod tumani",
    districtRu: "Юнусабадский район",
    districtEn: "Yunusabad district",
    mahallaUz: "Bog'ishamol MFY",
    mahallaRu: "сгм Богишамол",
    mahallaEn: "Bog'ishamol mahalla",
    streetUz: "Amir Temur shoh ko'chasi, 84-uy",
    streetRu: "проспект Амира Темура, д. 84",
    streetEn: "Amir Temur Avenue, bld. 84",
    landmarkUz: "Bodomzor metro bekati, Radisson mehmonxonasi yonida",
    landmarkRu: "м. Бодомзор, рядом с отелем Radisson",
    landmarkEn: "Near Bodomzar metro station, Radisson Hotel",
    lat: 41.3385,
    lng: 69.2842,
    accuracy: 4,
    defaultApt: "18",
    defaultFloor: "3",
    defaultEntrance: "2",
    defaultIntercom: "18K",
    substationUz: "4-sonli Yunusobod Tez Tibbiy Yordam podstansiyasi",
    substationRu: "Подстанция скорой помощи №4 (Юнусабад)",
    substationEn: "Emergency Medical Substation #4 (Yunusabad)",
    brigadeNumber: "#14",
    vehicleNumber: "01 404 TAA",
    vehicleModel: "GAZelle Next Reanimobil",
  },
  {
    id: "loc-chilonzor",
    nameUz: "Toshkent, Chilonzor tumani (20-mavze)",
    nameRu: "Ташкент, Чиланзарский район (20-й квартал)",
    nameEn: "Tashkent, Chilanzar district (20th Quarter)",
    districtUz: "Chilonzor tumani",
    districtRu: "Чиланзарский район",
    districtEn: "Chilanzar district",
    mahallaUz: "Katta Chilonzor MFY",
    mahallaRu: "сгм Катта Чиланзар",
    mahallaEn: "Katta Chilanzar mahalla",
    streetUz: "Muqimiy ko'chasi, 42-uy",
    streetRu: "улица Мукими, д. 42",
    streetEn: "Muqimiy street, bld. 42",
    landmarkUz: "Novza metro bekati, Korzinka supermarketiga yaqin",
    landmarkRu: "м. Новза, супермаркет Корзинка",
    landmarkEn: "Near Novza metro & Korzinka supermarket",
    lat: 41.2885,
    lng: 69.2152,
    accuracy: 3,
    defaultApt: "45",
    defaultFloor: "5",
    defaultEntrance: "1",
    defaultIntercom: "4545",
    substationUz: "7-sonli Chilonzor Tez Tibbiy Yordam podstansiyasi",
    substationRu: "Подстанция скорой помощи №7 (Чиланзар)",
    substationEn: "Emergency Medical Substation #7 (Chilanzar)",
    brigadeNumber: "#22",
    vehicleNumber: "01 812 TAA",
    vehicleModel: "Ford Transit Reanimatsiya",
  },
  {
    id: "loc-shaykhontohur",
    nameUz: "Toshkent, Shayxontohur tumani (Chorsu / Eski shahar)",
    nameRu: "Ташкент, Шайхантахурский район (Чорсу / Старый город)",
    nameEn: "Tashkent, Shaykhontohur district (Chorsu / Old City)",
    districtUz: "Shayxontohur tumani",
    districtRu: "Шайхантахурский район",
    districtEn: "Shaykhontohur district",
    mahallaUz: "Gulbozor MFY",
    mahallaRu: "сгм Гульбазар",
    mahallaEn: "Gulbozor mahalla",
    streetUz: "Navoiy ko'chasi, 12-uy",
    streetRu: "улица Навои, д. 12",
    streetEn: "Navoi street, bld. 12",
    landmarkUz: "Chorsu bozori va Ko'kaldosh madrasasi ro'parasida",
    landmarkRu: "напротив базара Чорсу и медресе Кукельдаш",
    landmarkEn: "Opposite Chorsu Bazaar and Kukeldash Madrasah",
    lat: 41.3255,
    lng: 69.2392,
    accuracy: 5,
    defaultApt: "7",
    defaultFloor: "2",
    defaultEntrance: "1",
    defaultIntercom: "7",
    substationUz: "1-sonli Shayxontohur Tez Yordam podstansiyasi",
    substationRu: "Подстанция скорой помощи №1 (Шайхантахур)",
    substationEn: "Emergency Medical Substation #1 (Shaykhontohur)",
    brigadeNumber: "#08",
    vehicleNumber: "01 230 TAA",
    vehicleModel: "Hyundai Staria Tez Tibbiy Yordam",
  },
  {
    id: "loc-mirzo-ulugbek",
    nameUz: "Toshkent, Mirzo Ulug'bek tumani (Buyuk Ipak Yo'li)",
    nameRu: "Ташкент, Мирзо-Улугбекский район (Буюк Ипак Йули)",
    nameEn: "Tashkent, Mirzo Ulugbek district (Buyuk Ipak Yoli)",
    districtUz: "Mirzo Ulug'bek tumani",
    districtRu: "Мирзо-Улугбекский район",
    districtEn: "Mirzo Ulugbek district",
    mahallaUz: "Olimlar MFY",
    mahallaRu: "сгм Олимлар",
    mahallaEn: "Olimlar mahalla",
    streetUz: "Buyuk Ipak Yo'li shoh ko'chasi, 110-uy",
    streetRu: "проспект Буюк Ипак Йули, д. 110",
    streetEn: "Buyuk Ipak Yoli Avenue, bld. 110",
    landmarkUz: "Buyuk Ipak Yo'li metro bekati, Sayohat mehmonxonasi",
    landmarkRu: "м. Буюк Ипак Йули, гостиница Саёхат",
    landmarkEn: "Near Buyuk Ipak Yoli metro, Sayohat Hotel",
    lat: 41.3262,
    lng: 69.3284,
    accuracy: 3,
    defaultApt: "29",
    defaultFloor: "4",
    defaultEntrance: "3",
    defaultIntercom: "029",
    substationUz: "3-sonli Mirzo Ulug'bek Tez Yordam podstansiyasi",
    substationRu: "Подстанция скорой помощи №3 (Мирзо Улугбек)",
    substationEn: "Emergency Medical Substation #3 (Mirzo Ulugbek)",
    brigadeNumber: "#31",
    vehicleNumber: "01 945 TAA",
    vehicleModel: "GAZelle Next Tez Tibbiy Yordam",
  }
];

export const mockDispatcherOtherCalls = [
  {
    id: "CALL-8910",
    code: "#UZ-103-8910",
    timeAgo: "2 daq oldin",
    callerPhone: "+998 97 712-44-33",
    district: "Yakkasaroy tumani",
    street: "Shota Rustaveli ko'chasi, 55",
    symptomKey: "symptomHeart",
    symptomLabelUz: "Yurak og'rig'i / Gipertoniya",
    priority: "HIGH",
    status: "en_route",
    brigade: "Brigada #05",
    eta: 4
  },
  {
    id: "CALL-8911",
    code: "#UZ-103-8911",
    timeAgo: "5 daq oldin",
    callerPhone: "+998 93 501-98-11",
    district: "Olmazor tumani",
    street: "Kichik halqa yo'li, 14",
    symptomKey: "symptomAccident",
    symptomLabelUz: "YTH jarohati",
    priority: "CRITICAL",
    status: "arrived",
    brigade: "Brigada #19",
    eta: 0
  }
];

export const quickSymptoms = [
  { id: "heart", labelKey: "symptomHeart", icon: "Activity", priority: "critical", color: "bg-red-50 text-red-700 border-red-300" },
  { id: "unconscious", labelKey: "symptomUnconscious", icon: "EyeOff", priority: "critical", color: "bg-red-50 text-red-700 border-red-300" },
  { id: "bleeding", labelKey: "symptomBleeding", icon: "Droplets", priority: "critical", color: "bg-rose-50 text-rose-700 border-rose-300" },
  { id: "breathing", labelKey: "symptomBreathing", icon: "Wind", priority: "critical", color: "bg-orange-50 text-orange-700 border-orange-300" },
  { id: "child", labelKey: "symptomChild", icon: "Baby", priority: "high", color: "bg-amber-50 text-amber-700 border-amber-300" },
  { id: "accident", labelKey: "symptomAccident", icon: "CarFront", priority: "critical", color: "bg-red-50 text-red-700 border-red-300" },
  { id: "stroke", labelKey: "symptomStroke", icon: "Brain", priority: "critical", color: "bg-purple-50 text-purple-700 border-purple-300" },
  { id: "other", labelKey: "symptomOther", icon: "HelpCircle", priority: "standard", color: "bg-slate-50 text-slate-700 border-slate-300" }
];
